export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const INITIAL_USER_PROFILE = "INITIAL_USER_PROFILE";
export const SUBMIT_USER_PROFILE = "SUBMIT_USER_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
